// src/app/layout.jsx

import './globals.css';
import { Inter } from 'next/font/google';
import Header from '../components/Header';
import React, { createContext, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

// Crear el Contexto de Transición
export const TransitionContext = createContext();

// Proveedor del Contexto de Transición
function TransitionContextProvider({ children }) {
  const [isTransitioning, setIsTransitioning] = useState(false);

  return (
    <TransitionContext.Provider value={{ isTransitioning, setIsTransitioning }}>
      {children}
    </TransitionContext.Provider>
  );
}

export const metadata = {
  title: 'React App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no',
  themeColor: '#000000',
  charset: 'utf-8',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionContextProvider>
          <Header />
          {children}
        </TransitionContextProvider>
      </body>
    </html>
  );
}
